services:
 mongo-ingredients:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_ingredient_data:/data/db

 mongo-users:
   image: mongo:latest
   ports:
     - 27018:27017
   volumes:
     - mongodb_user_data:/data/db
    
 mysql-recipe:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_recipe_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-rating:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_rating_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 ingredient-service:
  depends_on:
    - mongo-ingredients
  image: Recept-MS/ingredient-service
  ports:
    - 8080:8080
  links:
    - mongo-ingredients
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-ingredients

 user-service:
   depends_on:
     - mongo-users
   image: Recept-MS/user-service
   ports:
     - 8083:8083
   links:
     - mongo-users
   environment:
     MONGODB_PORT: 27018
     MONGODB_HOST: mongo-users
   
 rating-service:
  depends_on:
    - mysql-rating
  image: Recept-MS/rating-service
  ports:
    - 8082:8082
  links:
    - mysql-rating
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-rating
   MYSQL_DB_PORT: 3307

 recipe-service:
  depends_on:
    - ingredient-service
    - user-service
    - rating-service
  image: Recept-MS/recipe-service
  ports:
    - 8081:8081
  links:
    - ingredient-service
    - user-service
    - rating-service
  environment:
   INGREDIENT_SERVICE_BASEURL: ingredient-service:8080
   USER_SERVICE_BASEURL: user-service:8083
   RATING_SERVICE_BASEURL: rating-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-recipe
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - ingredient-service
     - recipe-service
   image: Recept-MS/api-gateway
   ports:
     - 8083:8083
   links:
     - ingredient-service
     - recipe-service
   environment:
     INGREDIENT_SERVICE_BASEURL: ingredient-service:8080
     RECIPE_SERVICE_BASEURL: recipe-service:8081

volumes:
 mongodb_ingredient_data:
 mongodb_user_data:
 mysql_rating_data:
 mysql_recipe_data: