services:
 mongo-ingredients:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_ingredient_data:/data/db
    
 mysql-recipe:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_recipe_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-rating:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_rating_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 ingredient-service:
  depends_on:
    - mongo-ingredients
  image: r0882755718/ingredient-service
  ports:
    - 8080:8080
  links:
    - mongo-ingredients
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-ingredients
   
 rating-service:
  depends_on:
    - mysql-rating
  image: r0882755718/rating-service
  ports:
    - 8082:8082
  links:
    - mysql-rating
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-rating
   MYSQL_DB_PORT: 3307

 recipe-service:
  depends_on:
    - rating-service
    - ingredient-service
  image: r0882755718/recipe-service
  ports:
    - 8081:8081
  links:
    - ingredient-service
    - rating-service
  environment:
   INGREDIENT_SERVICE_BASEURL: ingredient-service:8080
   RATING_INFO_SERVICE_BASEURL: rating-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-recipe
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - ingredient-service
     - recipe-service
   image: r0882755718/ede-api-gateway
   ports:
     - 8083:8083
   links:
     - ingredient-service
     - recipe-service
   environment:
     INGREDIENT_SERVICE_BASEURL: ingredient-service:8080
     RECIPE_SERVICE_BASEURL: recipe-service:8081

volumes:
 mysql_rating_data:
 mongodb_ingredient_data:
 mysql_inventory_data:
 mysql_recipe_data:
