server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: ingredient-service
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/ingredients
            - Method=POST
          filters:
            - SetPath=/api/ingredient
        - id: ingredient-service-all
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/ingredients
            - Method=GET
          filters:
            - SetPath=/api/ingredient/all
        - id: recipe-service
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/recipes
          filters:
            - SetPath=/api/recipe