server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: ingredient-service
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/ingredients
            - Method=GET
          filters:
            - SetPath=/api/ingredient

        - id: ingredient-service-all
          uri: http://${INGREDIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/ingredients/all
            - Method=GET
          filters:
            - SetPath=/api/ingredient/all

        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users
            - Method=GET
          filters:
            - SetPath=/api/user

        - id: user-service-all
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/all
            - Method=GET
          filters:
            - SetPath=/api/user/all

        - id: rating-service
          uri: http://${RATING_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ratings
            - Method=GET
          filters:
            - SetPath=/api/rating

        - id: rating-service-all
          uri: http://${RATING_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ratings/all
            - Method=GET
          filters:
            - SetPath=/api/rating/all

        - id: recipe-service
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/recipes
            - Method=GET
          filters:
            - SetPath=/api/recipe

        - id: recipe-service-all
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/recipes/all
            - Method=GET
          filters:
            - SetPath=/api/recipe/all

        - id: recipe-service-create
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/recipes
            - Method=POST
          filters:
            - SetPath=/api/recipe

        - id: recipe-service-edit
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/recipes
            - Method=PUT
          filters:
            - SetPath=/api/recipe

        - id: recipe-service-delete
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/recipes
            - Method=DELETE
          filters:
            - SetPath=/api/recipe