name: Build and deliver containers

on: push

jobs:
  recipeservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver recipe-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, test and package project
        working-directory: ./Recipe-service
        run: mvn package -DskipTests

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/recipe-service:latest ./Recipe-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/recipe-service:latest

      - name: Namespace
        uses: okteto/context@latest
        with:
          url: https://okteto.example.com
          token: ${{ secrets.OKTETO_TOKEN }}
    
      - name: "Create development environments namespace"
        uses: okteto/namespace@latest
        with:
          namespace: ede-thomasdceuster

      - name: Build
        uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: ${{ secrets.DOCKER_USERNAME }}/recipe-service:${{ github.sha }}
          namespace: ede-thomasdceuster

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ede-thomasdceuster
          
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ede-thomasdceuster
          manifest: k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/recipe-service:${{ github.sha }}
          waitOn: deployment/recipe-service

      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://recipe-service-ede-thomasdceuster.cloud.okteto.net"
          expected-statuses: "200"
  ingredientservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver ingredient-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./Ingredient-service
        run: mvn package -DskipTests

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/ingredient-service:latest ./Ingredient-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/ingredient-service:latest

      - name: Namespace
        uses: okteto/context@latest
        with:
          url: https://okteto.example.com
          token: ${{ secrets.OKTETO_TOKEN }}
    
      - name: "Create development environments namespace"
        uses: okteto/namespace@latest
        with:
          namespace: ede-thomasdceuster

      - name: Build
        uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: ${{ secrets.DOCKER_USERNAME }}/ingredient-service:${{ github.sha }}
          namespace: ede-thomasdceuster

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ede-thomasdceuster
          
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ede-thomasdceuster
          manifest: k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/ingredient-service:${{ github.sha }}
          waitOn: deployment/ingredient-service

      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://ingredient-service-ede-thomasdceuster.cloud.okteto.net"
          expected-statuses: "200"
  userservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver user-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
        
      - name: Build, test and package project
        working-directory: ./User-service
        run: mvn package -DskipTests
        
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/user-service:latest ./User-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/user-service:latest

      - name: Namespace
        uses: okteto/context@latest
        with:
          url: https://okteto.example.com
          token: ${{ secrets.OKTETO_TOKEN }}
    
      - name: "Create development environments namespace"
        uses: okteto/namespace@latest
        with:
          namespace: ede-thomasdceuster

      - name: Build
        uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }}
          namespace: ede-thomasdceuster

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ede-thomasdceuster
          
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ede-thomasdceuster
          manifest: k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }}
          waitOn: deployment/user-service

      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://user-service-ede-thomasdceuster.cloud.okteto.net"
          expected-statuses: "200"
  ratingservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver rating-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./Rating-service
        run: mvn package -DskipTests

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/rating-service:latest ./Rating-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/rating-service:latest

      - name: Namespace
        uses: okteto/context@latest
        with:
          url: https://okteto.example.com
          token: ${{ secrets.OKTETO_TOKEN }}
    
      - name: "Create development environments namespace"
        uses: okteto/namespace@latest
        with:
          namespace: ede-thomasdceuster

      - name: Build
        uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: ${{ secrets.DOCKER_USERNAME }}/rating-service:${{ github.sha }}
          namespace: ede-thomasdceuster

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ede-thomasdceuster
          
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ede-thomasdceuster
          manifest: k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/rating-service:${{ github.sha }}
          waitOn: deployment/rating-service

      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://rating-service-ede-thomasdceuster.cloud.okteto.net"
          expected-statuses: "200"
  apigateway:
      runs-on: ubuntu-latest
      name: Java 17 build, test, deliver api-gateway container
      steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./api-gateway
        run: mvn package -DskipTests

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/api-gateway:latest ./api-gateway

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/api-gateway:latest

      - name: Namespace
        uses: okteto/context@latest
        with:
          url: https://okteto.example.com
          token: ${{ secrets.OKTETO_TOKEN }}
  
      - name: "Create development environments namespace"
        uses: okteto/namespace@latest
        with:
          namespace: ede-thomasdceuster

      - name: Build
        uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}
          namespace: ede-thomasdceuster

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ede-thomasdceuster
        
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ede-thomasdceuster
          manifest: k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}
          waitOn: deployment/api-gateway

      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://api-gateway-ede-thomasdceuster.cloud.okteto.net"
          expected-statuses: "200"
