name: Build and deliver containers

on: push

jobs:
  recipeservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver recipe-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, test and package project
        working-directory: ./Recipe-service
        run: mvn package -DskipTests

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u unsecurytest --password-stdin

      - name: Docker Build
        run: docker build -t unsecurytest/recipe-service:latest ./Recipe-service

      - name: Upload container to Docker Hub with Push
        run: docker push unsecurytest/recipe-service:latest

  ingredientservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver ingredient-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./Ingredient-service
        run: mvn package -DskipTests

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u unsecurytest --password-stdin

      - name: Docker Build
        run: docker build -t unsecurytest/ingredient-service:latest ./Ingredient-service

      - name: Upload container to Docker Hub with Push
        run: docker push unsecurytest/ingredient-service:latest
  
  userservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver user-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
        
      - name: Build, test and package project
        working-directory: ./User-service
        run: mvn package -DskipTests
        
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u unsecurytest --password-stdin

      - name: Docker Build
        run: docker build -t unsecurytest/user-service:latest ./User-service

      - name: Upload container to Docker Hub with Push
        run: docker push unsecurytest/user-service:latest

  ratingservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver rating-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./Rating-service
        run: mvn package -DskipTests

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u unsecurytest --password-stdin
 
      - name: Docker Build
        run: docker build -t unsecurytest/rating-service:latest ./Rating-service

      - name: Upload container to Docker Hub with Push
        run: docker push unsecurytest/rating-service:latest

  apigateway:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver api-gateway container
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: maven
        distribution: adopt

    - name: Build, test and package project
      working-directory: ./api-gateway
      run: mvn package -DskipTests

    - name: Docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u unsecurytest --password-stdin

    - name: Docker Build
      run: docker build -t unsecurytest/api-gateway:latest ./api-gateway

    - name: Upload container to Docker Hub with Push
      run: docker push unsecurytest/api-gateway:latest
